# Github Action to run Performance Tests using JMeter
name: JMeter Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  jmeter:
    runs-on: ubuntu-latest
    env:
      JMETER_VERSION: "5.6"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Set up JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          ls -lah
      - name: Install JMeter Plugins
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.9/jmeter-plugins-manager-1.9.jar
          grep -lir 'jmeter-plugins-manager' . | xargs mv -t apache-jmeter-${{ env.JMETER_VERSION }}/lib/ext
          ls -lah apache-jmeter-${{ env.JMETER_VERSION }}
          ls -lah apache-jmeter-${{ env.JMETER_VERSION }}/lib/ext
          cd apache-jmeter-${{ env.JMETER_VERSION }}/bin
          ls -lah
          sh jmeter.sh --install-plugin jpgc-standard
          ls -lah
          ls -lah lib/ext
      - name: Run JMeter tests
        run: |
          cd apache-jmeter-${{ env.JMETER_VERSION }}/bin
          sh jmeter.sh -n -t path/Performance/sniffle.jmx -l test-results.jtl
          ls -lah
          ls -lah path
