# Github Action to run Performance Tests using JMeter
name: JMeter Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  FILE_UNDER_TEST: "Performance/sniffle.jmx"

jobs:
  jmeter:
    runs-on: ubuntu-latest
    env:
      JMETER_VERSION: "5.6"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Set up JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          ls -lah
      - name: Install JMeter Plugins
        env:
          PLUGINS_MNG_V: "1.9"
          CMD_RUNNER_V: "2.0"
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/${{ env.PLUGINS_MNG_V }}/jmeter-plugins-manager-${{ env.PLUGINS_MNG_V }}.jar
          wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/${{ env.CMD_RUNNER_V }}/cmdrunner-${{ env.CMD_RUNNER_V }}.jar
          grep -lir 'jmeter-plugins-manager' . | xargs mv -t apache-jmeter-${{ env.JMETER_VERSION }}/lib/ext
          grep -lir 'cmdrunner' . | xargs mv -t apache-jmeter-${{ env.JMETER_VERSION }}/lib
          ls -lah apache-jmeter-${{ env.JMETER_VERSION }}/lib
          ls -lah apache-jmeter-${{ env.JMETER_VERSION }}/lib/ext
          
          echo "-------------------- Compiling File ------------------------------"
          java -cp apache-jmeter-${{ env.JMETER_VERSION }}/lib/ext/jmeter-plugins-manager-${{ env.PLUGINS_MNG_V }}.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
          ls -lah apache-jmeter-${{ env.JMETER_VERSION }}/bin
          echo "------------------------------------------------------------------"
          pwd
          ls -lah
          echo "-------------------- File Created --------------------------------"
          sh apache-jmeter-${{ env.JMETER_VERSION }}/bin/PluginsManagerCMD.sh install-for-jmx /home/path/${{ env.FILE_UNDER_TEST }}
          ls -lah apache-jmeter-${{ env.JMETER_VERSION }}/bin
          ls -lah apache-jmeter-${{ env.JMETER_VERSION }}/bin/lib/ext
      - name: Run JMeter tests
        run: |
          sh apache-jmeter-${{ env.JMETER_VERSION }}/bin/jmeter.sh -n -t ${{ env.FILE_UNDER_TEST }} -l test-results.jtl
          ls -lah
          ls -lah path
