name: PR convention check

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
#    - name: Validate PR File
#      env: 
#        FILE_NAME: "README.md"
#      run: |
#        # Add your validation commands here
#        # Example: Check if a specific file exists in the PR
#        if ! git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }} | grep -q "${{ env.FILE_NAME }}"; then
#          echo "Error: '${{ env.FILE_NAME }}' is missing in the PR."
#          git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }}
#          exit 1
#        fi       
#        Add JIRA Ticket ID to your title e.g. "TAU-1"
        
    - name: Title Regex
      env: 
        REGEX: '^TAU-\d+\s.+'
      run: |
        echo "Error: 'path/to/file' is missing in the PR."
        title-regex: '^TAU-\d+\s.+'
        error-message: 'Add JIRA Ticket ID to your title e.g. "TAU-1"' 
        
    - name: Validate PR Title
      env: 
        REGEX: '^TAU-\d+\s.+'
      run: |
          # Get the PR title
          pr_title=$(git log --format=%s -n 1 ${{ github.event.pull_request.head.sha }})

          # Perform regex validation
          if ! [[ $pr_title =~ ${{ env.REGEX }} ]]; then
            echo "Error: PR title does not match the required pattern. Add please the JIRA Ticket - XXX"
            exit 1
          fi
