name: PR convention check

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
#    - name: Validate PR File
#      env: 
#        FILE_NAME: "README.md"
#      run: |
#        # Add your validation commands here
#        # Example: Check if a specific file exists in the PR
#        if ! git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }} | grep -q "${{ env.FILE_NAME }}"; then
#          echo "Error: '${{ env.FILE_NAME }}' is missing in the PR."
#          git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }}
#          exit 1
#        fi       
#        Add JIRA Ticket ID to your title e.g. "TAU-1"
        
        
    - name: Validate PR Title
      env: 
        REGEX: '^TAU-\d+\s.+'
      run: |
          echo "------------------------------------------------"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR: ${{ github.event.pull_request }}"
          echo "PR Head: ${{ github.event.pull_request.head }}"
          echo "PR Sha: ${{ github.event.pull_request.head.sha }}"
          echo "------------------------------------------------"
          echo "------------------------------------------------"
          echo "PR Sha: ${{ github.event.pull_request.number }}: The number of the pull request."
          echo "PR Sha: ${{ github.event.pull_request.title }}: The title of the pull request."
          echo "PR Sha: ${{ github.event.pull_request.body }}: The body content of the pull request."
          echo "PR Sha: ${{ github.event.pull_request.head }}: The branch or commit being merged into the base branch."
          echo "PR Sha: ${{ github.event.pull_request.head.ref }}: The branch or commit being merged into the base branch."
          echo "PR Sha: ${{ github.event.pull_request.head.sha }}: The branch or commit being merged into the base branch."
          echo "PR Sha: ${{ github.event.pull_request.head.repo }}: The branch or commit being merged into the base branch."
          echo "PR Sha: ${{ github.event.pull_request.base }}: The branch receiving the changes."
          echo "PR Sha: ${{ github.event.pull_request.user }}: The user who created the pull request."
          echo "PR Sha: ${{ github.event.pull_request.labels }}: An array of labels applied to the pull request."
          echo "PR Sha: ${{ github.event.pull_request.merged }}: Indicates whether the pull request has been merged."
          echo "PR Sha: ${{ github.event.pull_request.merged_by }}: The user who merged the pull request."
          echo "PR Sha: ${{ github.event.pull_request.merge_commit_sha }}: The SHA of the merge commit."
          echo "------------------------------------------------"
          # Get the PR title
          pr_title=${{ github.event.pull_request.title }}
          # Perform regex validation
          if [[ $pr_title =~ ${{ env.REGEX }} ]]; then
            echo "Matched!"
          else
            echo "Error: PR title does not match the required pattern. Add please the JIRA Ticket -  ${{ env.REGEX }}"
            exit 1
          fi
