name: show variables

on:
  workflow_dispatch:

jobs:
  variables_printing:
    runs-on: ubuntu-latest
    steps:
      - name: show event repository name
        run: echo ${{ github.event.repository.name }}
        
      - name: show repository
        run: echo ${{ github.repository }}
      - name: show repository
        run: |
          echo ${{github.api.url}}  |
          echo https://api.github.com/repos/tau-github-actions-for-testing/tau-digital-bank-e2e-tests/dispatches |
          echo ${{github.job}} |
          echo ${{github.repository}} |
          echo ${{github.repository.owner}}
        


